### ISSUE TITLE
[Test] FakePCIID for QCA9565

### ISSUE THREAD

**Issue by ItachiSan** [RehabMan/OS-X-Fake-PCI-ID#10]
Hello,
I just wanted to know how I could write a FakePCIID injector for my WLAN card.
I saw from [here](http://translate.google.com/translate?sl=ru&tl=en&js=n&prev=_t&hl=de&ie=UTF-8&u=https%3A%2F%2Fspreadsheets.google.com%2Fpub%3Fkey%3D0Arr23WYNror4dEc2T045WkFrbm56N0JfQVdiSU5jdHc%26hl%3Dru%26output%3Dhtml) (original source: [here](http://translate.google.com/translate?sl=ru&tl=en&js=n&prev=_t&hl=de&ie=UTF-8&u=https%3A%2F%2Fspreadsheets.google.com%2Fpub%3Fkey%3D0Arr23WYNror4dEc2T045WkFrbm56N0JfQVdiSU5jdHc%26hl%3Dru%26output%3Dhtml)) that I could **_PROBABLY**_ (I suppose to have a really few chances) that I could fake my device (**QCA9565** _[168c:0036]_) with the **AR9285** (_[168c:002b]_).
I know that probably (almost for sure) it won't work, but I wanted to give it a try.
I've been starting looking at your injectors, but I hope you could help me!

**Comment by RehabMan** [comment]
If you have an actual QCA9565 (AR9565), there is nothing FakePCIID can do to help you.  If you have an AR9285 that you plan to rebrand as an AR9565 to satisfy a BIOS whitelist requirement, then you can use FakePCIID to allow the drivers that would normally work with AR9285 work with your AR9285 rebranded as AR9565.

You should pattern it after one of the existing injectors such as FakePCIID_AR9280_as_AR946x.kext.

**Comment by ItachiSan** [comment]
I'm in the first case; I don't get why I can use it for my Ethernet PCI (in fact, [this works](https://github.com/RehabMan/OS-X-Fake-PCI-ID/blob/master/injectors/BCM57XX_as_BCM57765.plist)) but I can't tell OS X that my Wifi card could be another... Just to know why, I'm enough happy with my Ethernet :P

**Comment by RehabMan** [comment]
You cannot make AR9565 work by telling the system it is an AR9280 as the AR9565 is not compatible with software (the driver) written for AR9280.
