### ISSUE TITLE
FakePCIID XHCI Mux makes USB 3.0 ports unstable in 8-series and 9-series

### ISSUE THREAD

**Issue by dhnguyen92** [RehabMan/OS-X-Fake-PCI-ID#11]
I tried using XHCI Mux on 8-series laptops with 10.10, the USB wifi in 3.0 port is routed to EHCI correctly, but the result is USB wifi disconnected sometimes. I removed XHCI Mux and it is stable now.

In Macbook pro 2015, I even don't see EHCI controller. All USB 2.0 ports are controlled by XHCI.

**Comment by RehabMan** [comment]
If it doesn't work for your computer, don't use it.
