### ISSUE TITLE
FakePCIID with Ozmosis 1669M won't inject

### ISSUE THREAD

**Issue by ghost** [RehabMan/OS-X-Fake-PCI-ID#13]
Hello RehabMan

When using the following FakePCIID extensions:

FakePCIID.kext
FakePCIID_BCM57XX_as_BCM57765.kext
FakePCIID_XHCIMux.kext

Ozmosis 1669M fails to inject these Extensions from /EFI/Oz/Darwin/Extensions/Common/

The system just hangs on a black screen when booting, other kexts such as your branch of CodecCommander and FakeSMC work great as expected.

Do you have any ideas whats causing this? What logs/dumps might you need to help get this sorted out?

Is there anything else I can do to help?

Thanks in advanced.

Gratitude,
Robert aka Mrengles

**Comment by ghost** [comment]
I should have added that these Extensions inject just fine with Clover if that makes a difference...

**Comment by RehabMan** [comment]
No idea.  Must be a problem in your boot loader.  Even Clover has issues with some codeless kexts (but not this one, but for example certain configurations of BrcmPatchRAM).  Kexts should be installed to /L/E or /S/L/E anyway.

**Comment by ghost** [comment]
Thanks for the reply. I guess FakePCIID will fine a new home in /L/E
