### ISSUE TITLE
Rename FakePCIID_BCM57XX_as_BCM57765.kext

### ISSUE THREAD

**Issue by ghost** [RehabMan/OS-X-Fake-PCI-ID#14]
Hello RehabMan

Are you willing to rename FakePCIID_BCM57XX_as_BCM57765.kext like you have other extension names in the resent past? FakePCIID_Broadcom_Ethernet.kext would match up nicely with your other name changes.

Just a thought... 

Gratitude,

Robert aka Mrengles

**Comment by RehabMan** [comment]
That one reflects the function of the kext very well and I don't have to recommend it very often, so it is not an issue of trying to remember the name.

That's why I renamed only the Broadcom_WiFi and Intel_HD_Graphics.

**Comment by ghost** [comment]
That makes sense. I guess if I really want to change the name I can compile this project myself. Thanks again.

**Comment by RehabMan** [comment]
No need to compile it if you want to rename it.  Renaming files/folders is a basic function of Finder.
