### ISSUE TITLE
less a issue but a question

### ISSUE THREAD

**Issue by dreadkopp** [RehabMan/OS-X-Fake-PCI-ID#15]
hey rehabman,

i modified your code to get a injector working for the r9 390.

card sits in a real mac pro 3,1 and i'm not willig to change the amd kexts manually after every update.

i used the intel_hd_graphics injector as a template and changed it to this:

http://pastebin.com/fetRUbbF

however when installing the FakePCIID_R9_390_Graphics.kext and FakePCIID.kext the Mac will crash at boot until i remove the r9 390 and uninstall the kexts.

Can you give me a hint what i did wrong? Basically i just need the 390 (0x67b11002) to be recognized as a 290x (0x67b01002)

Cheers!

**Comment by RehabMan** [comment]
What changes were you making to the kexts prior to trying FakePCIID?
Perhaps you only need an injector kext?

**Comment by dreadkopp** [comment]
i just added the 390s device id to the info.plist of the AMD80000.kext / AMDRadeonX4000.kext.

nothing else. Poorly this way it would need to be redone after every update

**Comment by RehabMan** [comment]
No need for FakePCIID for that.  Just create an injector kext.
