### ISSUE TITLE
with FakePCIID_XHCIMux my external usb 3.0 hard drive not working

### ISSUE THREAD

**Issue by liuhangcheng** [RehabMan/OS-X-Fake-PCI-ID#18]
with FakePCIID_XHCIMux my external usb 3.0 hard drive not working, OS X 11.6

**Comment by RehabMan** [comment]
http://www.tonymacx86.com/threads/guide-10-11-usb-changes-and-solutions.173616/

**Comment by liuhangcheng** [comment]
t y
