### ISSUE TITLE
XHCIMux When there are no EHCI Controllers to Mix to

### ISSUE THREAD

**Issue by johnstray** [RehabMan/OS-X-Fake-PCI-ID#20]
I have a new Gigabyte GA-Z170-HD3 Motherboard that I'm trying to setup Sierra on. Whilst trying to figure out my USB side of things, I found that to enable all the ports that I need, I will not be able to remain under the 15 port limit.

With this board, all USB2 and USB3 are handled by the XHC controller. There is no EHCI Controllers appearing in IORegistryExplorer or anywhere in the extracted DSDT.

So, I thought I would give this project a go to see if this could help me, but there doesn't seem to be any support for the 100-Series XHC Controller (8086:a12f). 

Questions:
- When using the XHCIMux kext, does there need to be an EHCI controller present for it to mix to?
- Can the kexts be updated to support 100-Series Chipsets?

**Comment by RehabMan** [comment]
There is no EHCI controller with 100-series chipset.
You need to make compromises to stay under/at the 15-port limit.
