### ISSUE TITLE
Github download site down

### ISSUE THREAD

**Issue by dr3nan** [RehabMan/OS-X-Fake-PCI-ID#21]
Hi there RehabMan, your GitHub site is down, it shows error 404.. :(

**Comment by RehabMan** [comment]
github is working just fine here.
Perhaps you are referring to the bitbucket issue where you must add a trailing slash to reach the downloads list.
eg.
https://bitbucket.org/RehabMan/os-x-fake-pci-id/downloads
vs.
https://bitbucket.org/RehabMan/os-x-fake-pci-id/downloads/
As per this bitbucket issue:
https://bitbucket.org/site/master/issues/13894/repo-download-page-results-404-error-page

**Comment by dr3nan** [comment]
Ok, I feel kind of stupid :/...

I’ve been to your links for a long time and never experienced such thing.. BTW, great work! I’m now going crazy with a new kabylake setup and AMD RX cards, it’s not as easy as it may seems

Regards

Dolgar

**Comment by RehabMan** [comment]
You can help convince bitbucket to fix by voting up this issue:
https://bitbucket.org/site/master/issues/13894/repo-download-page-results-404-error-page

**Comment by dr3nan** [comment]
Done, thanks for the tip

BR

D

**Comment by RehabMan** [comment]
This has been fixed.
