### ISSUE TITLE
BCM94352z couldn't find WiFi networks

### ISSUE THREAD

**Issue by huangyz0918** [RehabMan/OS-X-Fake-PCI-ID#22]
I have a BCM94352z and I flashed a new BIOS whitelist to make it work in my Lenovo PC.

What i have done:

- I installed FakePCIID.kext and FakePCIID_Broadcom_WiFi.kext (WiFi) ,BrcmPatchRAM2.kext and BrcmFirmwareRepo.kext (Bluetooth) in SLE.

- I ran a shell script (wireless_bcm94352-110-v4.0c 2.command) which you can find at [wireless_half-mini](https://github.com/toleda/wireless_half-mini) to patch my Airport and 5 GHz

What i have got is that my computer can find my WiFi and Bluetooth (Can show it normally at Menu Bar but yellow in System Preferences/Network) and WiFi always in "Looking for networks" ,Bluetooth always in the "Loading" without a result.

![](https://ooo.0o0.ooo/2017/02/23/58aeec9115c86.png)

![](https://ooo.0o0.ooo/2017/02/23/58aeec9115d59.png)

This is my issue.

**Comment by RehabMan** [comment]
Make sure you have the correct 5ghz patch for your region/networking equipment.
Also, check your antenna connections.
This is not the appropriate place for troubleshooting your issue.
