### ISSUE TITLE
HD4400 desktop can not enable accelerate in macOS 10.12.4

### ISSUE THREAD

**Issue by zonyao** [RehabMan/OS-X-Fake-PCI-ID#23]
While I update system to 10.12.4, my cpu i3-4130 can not enable accelerate.

Please have a look this.

**Comment by RehabMan** [comment]
No information provided about what you're doing.
HD4400 requires the use of FakeID.
Your config.plist settings are probably wrong.
Not an issue with the kext.

**Comment by zonyao** [comment]
Hi RehabMan,


I put the kexts in /S/L/E, and restart, it's ok now.


Thanks.


But before only should put them in the EFI related folder.

________________________________
