### ISSUE TITLE
Adding support for Broadcom BCM94356ZAE?

### ISSUE THREAD

**Issue by huming2207** [RehabMan/OS-X-Fake-PCI-ID#24]
Hello Rehabman,

I've got a Lenovo Thinkpad X260 laptop, using Broadcom BCM94356ZAE wifi adapter, with **PCI Vendor ID 1434, Device ID 43ec**. I've tried it on macOS 10.12.4 using your latest kexts and it seems doesn't work. Now my laptop has been reinstalled back to windows, so I'm not sure where the issue exists.  But I've checked your `Broadcom_WiFi.plist` and I can't find this device ID (43ec). So...is it possible to add it directly into the plist?

Regards,
Jackson

**Comment by RehabMan** [comment]
Your device is not supported by the drivers in macOS (it has been tried, but failed).

**Comment by huming2207** [comment]
Okay, thanks for your reply. I'll buy a Dell DW1560 instead.
