### ISSUE TITLE
Force EHC to XHC

### ISSUE THREAD

**Issue by domeOo** [RehabMan/OS-X-Fake-PCI-ID#27]
Hello,
I'm wondering if there Is a way to reverse the functionality of the mux: To move the EHCI USB2.0 Ports to be handled by the XHC driver?
I have the problem, that the EHCI will ignore my usbConnector value of 0xff. (Maybe because the ports are children of a hub).

Thank you for your help.

**Comment by RehabMan** [comment]
The ability to answer your question depends on hardware details.
Use the forums.

FYI: UsbConnector is only for controller ports, not hub ports.
