### ISSUE TITLE
FakePCIID_XHCIMux.kext - no compatible dependency found for org.rehabman.driver.FakePCIID.

### ISSUE THREAD

**Issue by Lezardon** [RehabMan/OS-X-Fake-PCI-ID#28]
Hello

i found these errors when recreating the kernel cache:

Last login: Tue Jul  4 08:56:37 on console
MacBook-Air:~ manuel$ sudo touch /System/Library/Extensions && sudo kextcache -u /
Password:
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext Lilu.kext
FakePCIID_XHCIMux.kext - no compatible dependency found for org.rehabman.driver.FakePCIID.
FakePCIID_XHCIMux.kext is missing dependencies (including anyway; dependencies may be available from elsewhere)
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext FakePCIID_XHCIMux.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext FakePCIID_Intel_HD_Graphics.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext FakePCIID_Broadcom_WiFi.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext FakePCIID.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext ApplePS2Keyboard.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext ApplePS2Controller.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext ApplePS2SmartTouchPad.kext
kext-dev-mode allowing invalid signature -67013 0xFFFFFFFFFFFEFA3B for kext AppleMobileDevice.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext AppleBacklightInjector.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext PinConfigs.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext AppleALC.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext ACPIBatteryManager.kext
FakePCIID_XHCIMux.kext - no compatible dependency found for org.rehabman.driver.FakePCIID.
FakePCIID_XHCIMux.kext - no compatible dependency found for org.rehabman.driver.FakePCIID.
Prelink failed for org.rehabman.driver.FakePCIID.XHCIMux; omitting from prelinked kernel.
KernelCache ID: F9193654A6920FF2B623B392D52CCABC
MacBook-Air:~ manuel$ 

Could you advise what does it means ? Thank you

[error.zip](https://github.com/RehabMan/OS-X-Fake-PCI-ID/files/1120827/error.zip)

**Comment by RehabMan** [comment]
It means you have a FakePCIID kexts that are from different builds.
Must use matched set.
