### ISSUE TITLE
Certain colors of Blue in Safari crash Hackintosh

### ISSUE THREAD

**Issue by TylerD89** [RehabMan/OS-X-Fake-PCI-ID#29]
So randomly, I came across this issue where if you search oxycodone in Safari, I get a system wide freeze. I confirmed that this issue is caused by the special shade of blue that appears on the side of the webpage (see my screenshot from my iPhone that is attached). It appears that any time that Safari will display this color, it will immediately freeze the display. I would then have to hard power-off my computer. I have tried to recreate this issue in other Applications such as Chrome and Photoshop, but cannot recreate this error. 

Another thing, I can confirm that the built in drivers for the 4400 and my GTX 1050Ti are unaffected by this. 

Now down to specs and settings I am running:
H97 (UEFI) Chipset 1150
Intel Core i3 4160 with Intel HD 4400 Graphics

Current FakePCIID Kexts from RehabMan (Installed in /System/Library/Extensions and Clover/10.12/Kexts)
Intel GFX 0x04128086
ig-platform-id 0x0d220003

Clover and Screenshot attached!

And before judging me for searching oxycodone, I was simultaneously looking up what killed Heath Ledger and wanted to know what it was.
[Clover.zip](https://github.com/RehabMan/OS-X-Fake-PCI-ID/files/1233222/Clover.zip)

**Comment by RehabMan** [comment]
Use the forums... this is not the appropriate place to troubleshoot your issue.

Read FAQ, "Problem Reporting"
https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/
