### ISSUE TITLE
BCM43142

### ISSUE THREAD

**Issue by scris** [RehabMan/OS-X-Fake-PCI-ID#30]
My Broadcom Wi-Fi is **BCM43142(14e4,4365)**. It's not on your list. How can I do? Can I just write it into the "IOKitPersonalities" in the "Broadcom_WiFi.plist"? If I can't, how can I do?
Thank you.

**Comment by scris** [comment]
So how can I use my **14e4,4365**?

**Comment by scris** [comment]
![qq20170824-162634](https://user-images.githubusercontent.com/23412857/29657070-0fbc9ec6-88e9-11e7-8290-97a40808c5fb.png)
I got it from SystemInfo.
![qq20170824-162731](https://user-images.githubusercontent.com/23412857/29657122-364ae57a-88e9-11e7-8dc7-d9d87f45dea1.png)

**Comment by scris** [comment]
[BCM43142A0_001.001.011.0311.0312.hex.zip](https://github.com/RehabMan/OS-X-Fake-PCI-ID/files/1248181/BCM43142A0_001.001.011.0311.0312.hex.zip)
I have a "**BCM43142A0_001.001.011.0311.0312.hex**" in my Windows (in the "drivers"), is it helpful?
Actually, I have those drivers in Windows:
![qq20170824-163211](https://user-images.githubusercontent.com/23412857/29657351-e3da9f46-88e9-11e7-9286-700d4b96595d.png)

**Comment by scris** [comment]
And, is PCIDeviceStub.cpp a useful one?

**Comment by scris** [comment]
Well, are you here, RehabMan?

**Comment by scris** [comment]
![Uploading 7B94EC57624E7F45954B93DA4C915B4B.png…]()
Seem to be useful, but...I can't find the Wi-Fi in my mac just all same.

**Comment by scris** [comment]
![Broadcom](https://user-images.githubusercontent.com/23412857/29665348-4a7f0978-8906-11e7-8674-050e6955193a.jpg)
Seem to be useful......But actually, nothing happened, just the same as yesterday.

**Comment by RehabMan** [comment]
BCM43142 is not supported.
