### ISSUE TITLE
FakePCIID_BCM57XX_as_BCM57765.kext Does not work on 10.13

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [RehabMan/OS-X-Fake-PCI-ID#31]
BCM57785 does not work on 10.13.
On 10.12 and older - all OK.

**Comment by RehabMan** [comment]
You already reported this on the-darkvoid github.
Closing due to the fact it is a duplicate.
I have no hardware to test/debug this.  Maybe the-darkvoid does.
