### ISSUE TITLE
Latest FakePCIID_Intel_HD_Graphics.kext doesn't work with Intel HD510

### ISSUE THREAD

**Issue by heronimus** [RehabMan/OS-X-Fake-PCI-ID#32]
Hello Rehabman,

I have Intel HD510 on my Asus A456UR (proc: i5 6198DU) running Sierra 10.12.6. 
The graphics is working fine with your FakePCIID_Intel_HD_Graphics.kext 1.3.7 (2017-0425) with additional IntelGFX FakeID inject 0x19128086 on Clover. 

Then its broken with your FakePCIID_Intel_HD_Graphics.kext 1.3.8 and latest 1.3.9. 
I spot that you add id 0x19128086 on IOPCIPrimaryMatch to the new kext plist (1.3.8 and later). I don't know why it broke the QE/CI on this graphic card.  

Load the new kext (1.3.8-1.3.9) without injecting FakeID on Clover will result to no QE/CI display (It's show --> [IGPU] Graphics driver failed to load: could not register with Framebuffer driver! -- on Clover boot verbose log), while load the new kext with injecting FakeID 0x19128086 will result to full of glitch screen (It's seem QE/CI but with a ton of glitch artifact).

I have try to remove 0x19128086 from IOPCIPrimaryMatch on your latest kext, and load that with FakeID inject 0x19128086 on Clover, and the graphics card can load fine now.

---------------------------------------------------------------------------------------
I know it's uncommon graphic card used in market, and it will be hard for you to test if you don't have device with this graphic card. So I just want you know about this, and lookup the problem if necessary. Now i'm running well with the edited kext.

*Another info : I also used Lilu and IntelGraphicFixup, but it didnt change anything (Graphic still work fine with or without that).
Thankyou RehabMan, your work are always amazing.

Regards,
Heronimus.

**Comment by RehabMan** [comment]
HD510 not supported.  It is GT1.  No support in macOS or OS X for GT1/HD510.

Note if you wish to attempt to prove you have QE/CI working with HD510, use the forums to provide proof (ioreg, EFI/Clover).  While I think CI is possible, I don't think QE is.

With the older FakePCIID kext and FakeID injected as 0x1912, the kexts were not even loading.  Might as well not install them.

**Comment by heronimus** [comment]
Yeah thanks for the response, i just read about that on PikeRAlpha blog. I think I agree with you, so I was fortunate to get this graphic card at least operate able for me now.

By the way this is my copy of ioreg, some screenshot about graphic card, and clover folder if you want to lookup.
https://www.dropbox.com/s/s5fhbr58f33nwfx/heronimus-ihd510.zip?dl=0

Again, thankyou Rehabman.

**Comment by RehabMan** [comment]
OK, here's the deal... Your ioreg shows QE/CI working.

But FakePCIID is not loaded (as discussed, the old version does not match against 0x1916), so no need to install it in the first place.
I guess HD510 support has been added at some point to the native kexts (Apple planning an HD510 device?)
I would inject device-id 0x1902 via FakeID/IntelGFX=0x19028086 (which is supported natively and correponds to HD510), and no need for FakePCIID at all.  

Will leave FakePCIID as is as that is the intention: to spoof HD530 when it is installed.

**Comment by heronimus** [comment]
Ok I understand, that make sense.
 
And just for information, as long I remember this IHD510 starts work after 10.12.2 update. Before that I only get blank screen on my display.

Thanks a lot !

**Comment by ln8711** [comment]
hi, @heronimus 
So intel hd 510 works ok for you?

**Comment by heronimus** [comment]
@hoanglan87 Yes it works, even without FakePCIID, just inject the device-id with clover. You can check my ioreg, clover config, and some screenshoot on link I post before.

**Comment by ln8711** [comment]
Thanks for your update, it helps a lot man!

**Comment by golamrabbiazad** [comment]
followed the steps and graphics works (Intel HD Graphics 510 1536MB) **But, full glitches on display.** 
What to do? How to fix that glitches?

**Comment by heronimus** [comment]
@golamrabbiazad what device-id do you used to inject on Clover? also remember to remove FakePCIID_Intel_HD_Graphics.kext, you dont need that in the first place.

**Comment by golamrabbiazad** [comment]
@heronimus dev id was 19160000 & without this kext showed me the black screen! I had set fake id (19128086) in clover with injecting Intel graphics. Thanks for the reply.

**Comment by deepeshravani** [comment]
@heronimus @RehabMan  i tried this on my pc ( CPU - i3-6098P) 
I Installed High Sierra but Still Can't Go through installation Screen with full glitches on display
Waiting For Your Reply.

**Comment by DarkFighterLuke** [comment]
@heronimus at the moment I haven't kexts for intel graphics, only the fake id and it is not working (I have low resolution and no QE/CI). Do I need some kexts to make this card working?
