### ISSUE TITLE
BCM5788 - Sleeping Issue

### ISSUE THREAD

**Issue by Ocraftyone** [RehabMan/OS-X-Fake-PCI-ID#35]
When my hackintosh goes to sleep, when it wakes back up, it says that the ethernet cable has been disconnected when it is still plugged in. This is only fixed by a reboot, then the ethernet works again until it sleeps again.

**Comment by RehabMan** [comment]
You should use the forums.
Your configuration (ACPI, clover, kext install procedures, etc) is likely incorrect.
