### ISSUE TITLE
FakePCIID & FakePCIID_Intel_HDMI_Audio stop sleep on 300 series Motherboard

### ISSUE THREAD

**Issue by gymnae** [RehabMan/OS-X-Fake-PCI-ID#38]
Thank to your most recent release, I do get sound working with the ALC887 codec installed, but then the machine immediately wakes up after having turned off.
Without those kexts, this problem doesn't exist.

**Comment by gymnae** [comment]
I'd like to close this, since it's not FakePCIID alone, but in combination with AppleALC and Lilu, which are not in scope of this

**Comment by RehabMan** [comment]
Sounds like "auto restart after shutdown".
See XHC.PMEE fix in my laptop patch repo.

**Comment by gymnae** [comment]
Thanks, 
I used that patch together with: 

- USB_PRW 0x0D Skylake (instant wake) 
- manual change of _PWR to GLAN and CVWN

Now it sleeps properly once, after the first wake up sleep is unreliable.
