### ISSUE TITLE
Wi-Fi settings on Dell LATITUDE E7440

### ISSUE THREAD

**Issue by Aldeab** [RehabMan/OS-X-Fake-PCI-ID#40]
Hi

I have seen many explanations that confirm that it is possible to work with you Wi-Fi

  Without having to use an external card!

I tried and did not work with me any way

Maybe the reason I did not do it right?

// Can you give me the right way to do it \\

I desperately need your help, my friendMy device:

Dell LATITUDE

Core i-5 4th Gen

RAM 8 GB

256 GB SSD

btw I'm on High Sierra 10.13

**Comment by RehabMan** [comment]
You should use the forums (you didn't even mention which WiFi chipset you have!).
